name: Auto Comment on New Issue

on:
  issues:
    types: [opened]

jobs:
  add-comment:
    if: >
      github.event.issue.comments == 0 && 
      contains(github.event.issue.labels.*.name, 'paper')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Post welcome comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            _Use this meta-comment to react to this paper_
